version: 2
updates:
  # Configure updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "npm"
      - "dependencies"
      - "security"
    reviewers:
      - "EpochCore5/administrators"
    assignees:
      - "EpochCore5/administrators"
    commit-message:
      prefix: "npm"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*test*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*eslint*"
          - "*prettier*"
          - "*test*"
        update-types:
          - "minor"
          - "patch"
    
  # Configure updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "pip"
      - "dependencies"
      - "security"
    reviewers:
      - "EpochCore5/administrators"
    assignees:
      - "EpochCore5/administrators"
    commit-message:
      prefix: "pip"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "*pytest*"
          - "*lint*"
          - "*test*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*pytest*"
          - "*lint*"
          - "*test*"
        update-types:
          - "minor"
          - "patch"
          
  # Configure updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
      - "dependencies"
    reviewers:
      - "EpochCore5/administrators"
    assignees:
      - "EpochCore5/administrators"
