name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate icons
      run: |
        python scripts/generate_icons.py
        echo "Generated icons:"
        ls -la assets/icons/
    
    - name: Commit generated assets
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/icons/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-generated icons [skip ci]"
          git push
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Create deployment package
      run: |
        mkdir -p _site
        cp index.html _site/
        cp -r assets _site/ 2>/dev/null || echo "No assets directory to copy"
        # Create a simple index page that shows the generated icons
        cat > _site/icons.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Generated Icons - Demo Repository</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                .icon-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; }
                .icon-item { text-align: center; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
                .icon-item img { max-width: 100%; height: auto; }
            </style>
        </head>
        <body>
            <h1>Generated Icons</h1>
            <p>These icons are automatically generated by the CI/CD pipeline.</p>
            <div class="icon-grid">
        EOF
        
        # Add icon entries if they exist
        if [ -d "assets/icons" ]; then
          for icon in assets/icons/*.png; do
            if [ -f "$icon" ]; then
              filename=$(basename "$icon")
              echo "<div class=\"icon-item\"><img src=\"$icon\" alt=\"$filename\"><br><strong>$filename</strong></div>" >> _site/icons.html
            fi
          done
        fi
        
        echo "</div></body></html>" >> _site/icons.html
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '_site'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
    
    - name: Create release artifacts
      if: github.event_name == 'release'
      run: |
        # Create a zip of generated icons for releases
        cd assets && zip -r ../icons-${{ github.ref_name }}.zip icons/
    
    - name: Upload release assets
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./icons-${{ github.ref_name }}.zip
        asset_name: icons-${{ github.ref_name }}.zip
        asset_content_type: application/zip